/**
 * Bundle the server logic and the sim into one ES module the Edge Function
 * imports: supabase/functions/_shared/server.js. Generated, gitignored; run
 * before every deploy (`npm run deploy -w @jones2/server` does both).
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const root = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));

await build({
  entryPoints: [root('src/index.ts')],
  outfile: root('../../supabase/functions/_shared/server.js'),
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  mainFields: ['module', 'main'],
  banner: { js: '// GENERATED by packages/server/tools/bundle.ts. Do not edit; do not commit.' },
  logLevel: 'info',
});
